### ISSUE TITLE
Difference of the main module between paper and code 

### ISSUE THREAD

**Issue by WangQinghuCS** [mrlibw/ManiGAN#4]
Hi, I read your paper and code. I am confused about the main module.In the paper, there is only ACM module without attention in the main module. However, in your code, i find that you  use the attention in both main module and the DCM module.I wonder I should follow the code or the paper?

**Comment by VicZlq** [comment]
您好，我最近在复现这篇论文的代码，在训练DAMSM的时候出现了一些问题
当我输入：python pretrain_DAMSM.py --cfg cfg/DAMSM/bird.yml --gpu 0
会出现错误Traceback (most recent call last):
  File "pretrain_DAMSM.py", line 270, in <module>
    dataset.ixtoword, image_dir)
  File "pretrain_DAMSM.py", line 124, in train
    ixtoword, attn_maps, att_sze)
  File "/home/zhaoliuqing/ManiGAN-master/ManiGAN-master/code/miscc/utils.py", line 145, in build_super_images
    PIL_att = Image.fromarray(np.uint8(one_map))
  File "/home/anaconda3/envs/pt/lib/python3.7/site-packages/PIL/Image.py", line 2716, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey)
TypeError: Cannot handle this data type: (1, 1, 48), |u1
不知道您有没有遇到过同样的错误？如果遇到过，请问是如何解决的？十分感谢

**Comment by hs457681503** [comment]
> 您好，我最近在复现这篇论文的代码，在训练DAMSM的时候出现了一些问题
> 当我输入：python pretrain_DAMSM.py --cfg cfg/DAMSM/bird.yml --gpu 0
> 会出现错误Traceback (most recent call last):
> File "pretrain_DAMSM.py", line 270, in
> dataset.ixtoword, image_dir)
> File "pretrain_DAMSM.py", line 124, in train
> ixtoword, attn_maps, att_sze)
> File "/home/zhaoliuqing/ManiGAN-master/ManiGAN-master/code/miscc/utils.py", line 145, in build_super_images
> PIL_att = Image.fromarray(np.uint8(one_map))
> File "/home/anaconda3/envs/pt/lib/python3.7/site-packages/PIL/Image.py", line 2716, in fromarray
> raise TypeError("Cannot handle this data type: %s, %s" % typekey)
> TypeError: Cannot handle this data type: (1, 1, 48), |u1
> 不知道您有没有遇到过同样的错误？如果遇到过，请问是如何解决的？十分感谢

我出现了和你一样的问题，可以发给我你的qq号码吗？

**Comment by markywg** [comment]
> Hi, I read your paper and code. I am confused about the main module.In the paper, there is only ACM module without attention in the main module. However, in your code, i find that you use the attention in both main module and the DCM module.I wonder I should follow the code or the paper?

I suppose that this model has inherited some features of ControlGAN, which is optimized over AttnGAN, so that the paper neglects some details in constructing attention. It is recommended to read the relevant papers.

**Comment by liuwanqingqing** [comment]
> > 您好，我最近在复现这篇论文的代码，在训练DAMSM的时候出现了一些问题 当我输入：python pretrain_DAMSM.py --cfg cfg/DAMSM/bird.yml --gpu 0 会出现错误Traceback （latest call last）： 文件“pretrain_DAMSM.py”，第 270 行，在 dataset.ixtoword， image_dir） 文件“pretrain_DAMSM.py”，第 124 行，在火车 ixtoword，attn_maps，att_sze） 文件“/home/zhaoliuqing/ManiGAN-master/ManiGAN-master/code/miscc/utils.py”，第 145 行，在 build_super_imagesPIL_att = Image.fromarray（np.uint8（one_map）） 文件“/home/anaconda3/envs/pt/lib/python3.7/site-packages/PIL/Image.py”，第 2716 行，在 fromarray raise TypeError（“无法处理此数据类型：%s， %s” % typekey） TypeError：无法处理此数据类型：（1， 1， 48）， |u1 不知道您有没有遇到过同样的错误？如果遇到过，请问是如何解决的？十分感谢
> 
> 我出现了和你一样的问题，可以发给我你的qq号码吗？
I also face the above problems, is there a feasible solution

**Comment by VicZlq** [comment]
抱歉才看到邮件，这篇工作是我硕士期间复现的内容。您的这个报错似乎是数据处理的问题，我记得在作者前几篇工作的issue内我似乎找到过解决方法。您可以去git上查找一下。希望可以帮助到您

---- Replied Message ----
| From | ***@***.***> |
| Date | 04/07/2024 11:45 |
| To | mrlibw/ManiGAN ***@***.***> |
| Cc | ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [mrlibw/ManiGAN] Difference of the main module between paper and code (#4) |

您好，我最近在复现这篇论文的代码，在训练DAMSM的时候出现了一些问题 当我输入：python pretrain_DAMSM.py --cfg cfg/DAMSM/bird.yml --gpu 0 会出现错误Traceback （latest call last）： 文件“pretrain_DAMSM.py”，第 270 行，在 dataset.ixtoword， image_dir） 文件“pretrain_DAMSM.py”，第 124 行，在火车 ixtoword，attn_maps，att_sze） 文件“/home/zhaoliuqing/ManiGAN-master/ManiGAN-master/code/miscc/utils.py”，第 145 行，在 build_super_imagesPIL_att = Image.fromarray（np.uint8（one_map）） 文件“/home/anaconda3/envs/pt/lib/python3.7/site-packages/PIL/Image.py”，第 2716 行，在 fromarray raise TypeError（“无法处理此数据类型：%s， %s” % typekey） TypeError：无法处理此数据类型：（1， 1， 48）， |u1 不知道您有没有遇到过同样的错误？如果遇到过，请问是如何解决的？十分感谢

我出现了和你一样的问题，可以发给我你的qq号码吗？
I also face the above problems, is there a feasible solution
