### ISSUE TITLE
TypeError: Cannot handle this data type: (1, 1, 12), |u1

### ISSUE THREAD

**Issue by VicZlq** [mrlibw/ManiGAN#8]
Thanks for your project,！
when I was reproducing the code, there were some problems：
Traceback (most recent call last):
  File "main.py", line 214, in <module>
    gen_example(dataset.wordtoix, algo, imsize_list, image_transform, norm, data_dir)  # generate images for customized captions
  File "main.py", line 137, in gen_example
    algo.gen_example(data_dic)
  File "/home/zhaoliuqing/ManiGAN-master/ManiGAN-master/code/trainer.py", line 615, in gen_example
    [attn_maps[j]], att_sze)
  File "/home/zhaoliuqing/ManiGAN-master/ManiGAN-master/code/miscc/utils.py", line 241, in build_super_images2
    PIL_att = Image.fromarray(np.uint8(one_map))
  File "/home/anaconda3/envs/pt/lib/python3.7/site-packages/PIL/Image.py", line 2716, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey)
TypeError: Cannot handle this data type: (1, 1, 12), |u1
Have you encountered the same problem? How to solve it? Thank you!

**Comment by devShaurya** [comment]
Hi @VicZlq I am facing the same error. Did you find any solution for this? I wonder how others were able to run the training or testing. If anyone has the solution please post it here.

**Comment by devShaurya** [comment]
I don't know whether this is a solution or not but I tried with python 2.7 and code was working. @VicZlq could you try with python2.7.

**Comment by VicZlq** [comment]
@devShaurya Thank you very much for your suggestions. I haven't solved this problem yet. What version of pytorch nltk PIL do you install under version 2.7? Thanks a lot!

**Comment by devShaurya** [comment]
PIL is 4.3.0 and nltk is 3.2.5. There would be some issues in pickle.load() but you will be easily able to solve those. @mrlibw Could you confirm that using python 2.7 is correct solution? @VicZlq if you find other solution please post it here.

**Comment by VicZlq** [comment]
thank you! I am currently testing with the 2.7 environment, and I just encountered the problem of pickle.load(). How did you solve it then? Is it a problem with the pickle package?@devShaurya

**Comment by devShaurya** [comment]
hi @VicZlq! I had problem on line 273 in datasets.py file. I removed the encoding argument in it and then it worked fine.

**Comment by VicZlq** [comment]
@devShaurya Very magical solution! I have been able to run through the code, if I find a solution for version 3.7, I will post it here!

**Comment by hs457681503** [comment]
> Hi @VicZlq I am facing the same error. Did you find any solution for this? I wonder how others were able to run the training or testing. If anyone has the solution please post it here.

**Comment by hyungkwonko** [comment]
I guess it may too late to answer this, but since I had the same problem, here is the solution that worked for me.

**Solution**
in line 130 of code/miscc/utils.py, add **_multichannel=True_** at the end
before: upscale=vis_size // att_sze)
after: upscale=vis_size // att_sze, multichannel=True)

**My Environment**
python 3.8.6
pillow 7.2.0
scikit-image 0.17.2

**Comment by sondn141** [comment]
@hyungkwonko your solution did save my day, thank u very much.

**Comment by liuwanqingqing** [comment]
I also face the above problems, and the above solution is still not feasible for me. Is there any feasible solution？

**Comment by escapistmost** [comment]
> I also face the above problems, and the above solution is still not feasible for me. Is there any feasible solution？

maybe it's late for you ,but the change  he refer to not only in line 130, but also 231

**Comment by liuwanqingqing** [comment]
> > I also face the above problems, and the above solution is still not feasible for me. Is there any feasible solution？
> 
> maybe it's late for you ,but the change he refer to not only in line 130, but also 231
感谢解答。在尝试后发现仍然报错：TypeError: pyramid_expand() got an unexpected keyword argument 'multichannel'

**Comment by escapistmost** [comment]
你看看是不是版本放错了，我运行的没报这个错，我一会儿去看看python版本








 ----------Reply to Message----------
 On Wed, Oct 9, 2024 20:19 PM ***@***.***&gt; wrote:

  

   
I also face the above problems, and the above solution is still not feasible for me. Is there any feasible solution？
  
maybe it's late for you ,but the change he refer to not only in line 130, but also 231
 感谢解答。在尝试后发现仍然报错：TypeError: pyramid_expand() got an unexpected keyword argument 'multichannel'

**Comment by liuwanqingqing** [comment]
好的，感谢，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mrlibw/ManiGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月10日(星期四) 上午9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mrlibw/ManiGAN] TypeError: Cannot handle this data type: (1, 1, 12), |u1 (#8)





 你看看是不是版本放错了，我运行的没报这个错，我一会儿去看看python版本 
 
 
 
 
 
 
 
 
  ----------Reply to Message---------- 
  On Wed, Oct 9, 2024 20:19 PM ***@***.***&amp;gt; wrote: 
 
    
 
     
 I also face the above problems, and the above solution is still not feasible for me. Is there any feasible solution？ 
    
 maybe it's late for you ,but the change he refer to not only in line 130, but also 231 
  感谢解答。在尝试后发现仍然报错：TypeError: pyramid_expand() got an unexpected keyword argument 'multichannel'

**Comment by escapistmost** [comment]
> 好的，感谢，
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mrlibw/ManiGAN" ***@***.***&gt;; 发送时间:&nbsp;2024年10月10日(星期四) 上午9:20 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [mrlibw/ManiGAN] TypeError: Cannot handle this data type: (1, 1, 12), |u1 (#8) 你看看是不是版本放错了，我运行的没报这个错，我一会儿去看看python版本
> ----------Reply to Message---------- On Wed, Oct 9, 2024 20:19 PM ***@***.***&amp;gt; wrote: I also face the above problems, and the above solution is still not feasible for me. Is there any feasible solution？ maybe it's late for you ,but the change he refer to not only in line 130, but also 231 感谢解答。在尝试后发现仍然报错：TypeError: pyramid_expand() got an unexpected keyword argument 'multichannel' — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Pillow 8.4.0
scikit-image 0.17.2
